[project]
name = "autopub-test"
version = "0.21.6"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.autopub]
plugins = ["autopub_plugins.github", "autopub.plugins.uv"]
