[project]
name = "autopub-test"
version = "0.20.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.autopub]
plugins = [
    "autopub_plugins.github",
    "autopub.plugins.bump_version",
    "autopub.plugins.uv",
]
