[project]
name = "test-project-v1"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.autopub]
plugins = ["autopub_plugins.github"]
